apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-2025
images:
- name: 135808912790.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 135808912790.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: d436c0c5
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
